# Generated by Django 4.2.20 on 2025-03-13 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdetails',
            options={'verbose_name': 'Patient Detail', 'verbose_name_plural': 'Patient Details'},
        ),
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('contact_info', models.EmailField(max_length=150)),
                ('specialty', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Orthopedics', 'Orthopedics'), ('Neurology', 'Neurology'), ('Ophthalmology', 'Ophthalmology'), ('Otolaryngology', 'Otolaryngology'), ('Dermatology', 'Dermatology'), ('Gynecology', 'Gynecology'), ('Urology', 'Urology')], max_length=20)),
                ('about', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Detail',
                'verbose_name_plural': 'Doctor Details',
            },
        ),
    ]
