# Generated by Django 4.2.20 on 2025-03-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_patientdetails_options_doctordetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
    ]
